In [1]:
import cv2
import numpy as np
import os
import random

In [69]:
path = "D:/Code/NHAP_MON_AI/Project/BLS/dataset/train"
path2 = "D:/Code/NHAP_MON_AI/Project/BLS/dataset_copy/train"
ls = os.listdir(path)  
for folder in ls:
    path_file = os.listdir(f"{path}/{folder}")
    for name in path_file:
        path_img = f"{path}/{folder}/{name}"
        image = cv2.imread(path_img)
        image_gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
        image_gray = cv2.resize(image_gray, (75, 100), interpolation=cv2.INTER_AREA)
        image_gray = image_gray.astype(np.float32)
        # cv2.normalize(image_gray, image_gray, 0, 1.0, cv2.NORM_MINMAX)
        target_folder = f"{path2}/{folder}"
        if not os.path.exists(target_folder):
            os.makedirs(target_folder)
        cv2.imwrite(f"{target_folder}/{name}", image_gray)
        print(f"{path2}/{folder}/{name}")
        

D:/Code/NHAP_MON_AI/Project/BLS/dataset_copy/train/A/image_0.jpg
D:/Code/NHAP_MON_AI/Project/BLS/dataset_copy/train/A/image_1.jpg
D:/Code/NHAP_MON_AI/Project/BLS/dataset_copy/train/A/image_10.jpg
D:/Code/NHAP_MON_AI/Project/BLS/dataset_copy/train/A/image_11.jpg
D:/Code/NHAP_MON_AI/Project/BLS/dataset_copy/train/A/image_12.jpg
D:/Code/NHAP_MON_AI/Project/BLS/dataset_copy/train/A/image_13.jpg
D:/Code/NHAP_MON_AI/Project/BLS/dataset_copy/train/A/image_14.jpg
D:/Code/NHAP_MON_AI/Project/BLS/dataset_copy/train/A/image_15.jpg
D:/Code/NHAP_MON_AI/Project/BLS/dataset_copy/train/A/image_16.jpg
D:/Code/NHAP_MON_AI/Project/BLS/dataset_copy/train/A/image_17.jpg
D:/Code/NHAP_MON_AI/Project/BLS/dataset_copy/train/A/image_18.jpg
D:/Code/NHAP_MON_AI/Project/BLS/dataset_copy/train/A/image_19.jpg
D:/Code/NHAP_MON_AI/Project/BLS/dataset_copy/train/A/image_2.jpg
D:/Code/NHAP_MON_AI/Project/BLS/dataset_copy/train/A/image_20.jpg
D:/Code/NHAP_MON_AI/Project/BLS/dataset_copy/train/A/image_21.jpg
D:/Code/NHAP_

In [35]:
char_to_num = {chr(i): i - ord('A') for i in range(ord('A'), ord('Z') + 1)}
print(char_to_num)
path2 = "D:/Code/NHAP_MON_AI/Project/BLS/dataset_copy/train"
ls = os.listdir(path2)
target = np.eye(len(ls))
X = []
Y = []
for folder in ls:
    path_file = os.listdir(f"{path2}/{folder}")
    for name in path_file:
        path_img = f"{path2}/{folder}/{name}"
        image = cv2.imread(path_img, cv2.IMREAD_GRAYSCALE)
        image = image.astype(np.float32)
        image = cv2.normalize(image, image, 0, 1.0, cv2.NORM_MINMAX)
        image = image.reshape((1, 7500))
        # print(image)
        image = image[0]
        # print(image)
        X.append(image)
        Y.append(target[char_to_num[folder]])
train_sample = zip(X, Y)
train_sample = list(train_sample)
random.shuffle(train_sample)
X, Y = zip(*train_sample)
X = np.array(X)
Y = np.array(Y)
print(X)
print(Y)


{'A': 0, 'B': 1, 'C': 2, 'D': 3, 'E': 4, 'F': 5, 'G': 6, 'H': 7, 'I': 8, 'J': 9, 'K': 10, 'L': 11, 'M': 12, 'N': 13, 'O': 14, 'P': 15, 'Q': 16, 'R': 17, 'S': 18, 'T': 19, 'U': 20, 'V': 21, 'W': 22, 'X': 23, 'Y': 24, 'Z': 25}
[[0.6628571  0.6742857  0.6857143  ... 0.40571427 0.40571427 0.38285714]
 [0.84269667 0.8146067  0.7977528  ... 0.66853935 0.6853933  0.64044946]
 [0.67346936 0.65816325 0.64285713 ... 0.88265306 0.88265306 0.88265306]
 ...
 [0.10869565 0.22173911 0.38260868 ... 0.84347826 0.84347826 0.84347826]
 [0.8235294  0.81447965 0.8054299  ... 0.32579187 0.32126698 0.32126698]
 [0.6943232  0.68558955 0.6724891  ... 0.30567688 0.30131006 0.30131006]]
[[0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [ ]:
from sklearn.neural_network import MLPClassifier
mlp = MLPClassifier(hidden_layer_sizes=(7000, 5000, 2000, 1000), activation='logistic', solver='adam',batch_size=30, max_iter=1000)
mlp.fit(X,Y)
